server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/lottery?useUnicode=true
    username: root
    password: root

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

# Dubbo 广播方式配置
dubbo:
  application:
    name: Lottery
    version: 1.0.0
    register-mode: instance
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: tri
    port: 20880
  scan:
    base-packages: com.hjp.lottery.rpc